### ISSUE TITLE
[API Feature Request] SkillAPIPlayerDataLoadEvent

### ISSUE THREAD

**Issue by Lix3nn53** [Eniripsa96/SkillAPIKotlin#2]
I am trying to develop a mmorpg server using SkillAPI as a base. (https://github.com/Lix3nn53/GuardiansOfAdelia)

I need to load player data according to some SkillAPI data. So I need to wait for SkillAPI to load player's data first. So I added a 2 seconds delay before my data loading starts. 

It would be much more healthy for me to load data on SkillAPIPlayerDataLoadEvent. But It must be called even if player doesnt have any data. It would just let me know SkillAPI finished everything about loading this player's data.

Thanks in advance

**Comment by Eniripsa96** [comment]
One thing you could do is hook into the join handlers I have set up for after the player's data is initialized. 
See the following bits of code:
- [where it's called from](https://github.com/Eniripsa96/SkillAPI/blob/master/src/com/sucy/skill/listener/MainListener.java#L143)
- [example of hooking into it](https://github.com/Eniripsa96/SkillAPI/blob/master/src/com/sucy/skill/listener/BarListener.java#L76)

That is called regardless of whether it was able to find data or not, just as requested.
