### ISSUE TITLE
[Feature] Value Round

### ISSUE THREAD

**Issue by Zicerite** [Eniripsa96/SkillAPIKotlin#5]
I have a request for the remake.

It is just a mechanic that rounds a Value to the nearest Integer, or even to the nearest tenth, or hundredth.

**Comment by Eniripsa96** [comment]
There won't be mechanics like "Value Add", "Value Subtract", etc. anymore, instead, there will be full formula support for numeric values with any of the functions/operators defined [here](https://github.com/Eniripsa96/SkillAPI/wiki/_SkillAPI-Formulas)

**Comment by Zicerite** [comment]
Oh that is so much nicer, thank you!

**Comment by Eniripsa96** [comment]
I'll add in some logic to convert those to a generic Value mechanic. Examples from current mechanics:

**before** -> **after**
- Value Add "3" -> Value "key + 3"
- Value Health "current" -> Value "target.health"
- Value Health "percent" -> Value "target.health / target.maxHealth"

**Comment by Zicerite** [comment]
The gate of possibilities has somehow opened further thanks to this, thank you.
